using GLMakie, Colors, Random
Random.seed!(435)
fig = Figure(backgroundcolor = :ivory) # named colors
Box(fig[1, 1:3]; color=rand(RGBAf), strokecolor=rand(RGBf))
Box(fig[2, 1:3]; color=rand(RGBAf), strokecolor=rand(RGBf))
Box(fig[3, 1:3]; color=rand(RGBAf), strokecolor=rand(RGBf))
Box(fig[1:3, 1]; color=:transparent, strokecolor=:black, strokewidth = 2)
Box(fig[1:3, 2]; color=:transparent, strokecolor=rand(RGBf))
Box(fig[1:3, 3]; color=:transparent, strokecolor=rand(RGBf))
Box(fig[:, 3, Right()]; color=(:orangered, 0.15))
Label(fig[:, 3, Right()],"protrusion",textsize=18,rotation = π/ 2,padding=(3, 3, 3, 3))
Box(fig[1, 1:3, Bottom()]; color=rand(RGBAf))
Label(fig[1, 2, Bottom()], "protrusion")
Box(fig[1:3, 1, TopLeft()]; color = (:white, 0.95))
Label(fig[1:3, 1, TopLeft()], "(a)"; textsize=18, padding=(2, 2, 2, 2))
Colorbar(fig[:,end+1])
Label(fig[4,:], "My set of boxes")
Label(fig[0,:],"Basic Layout",textsize=24,color=:steelblue4,font="TeX Gyre Heros Bold")
colgap!(fig.layout, 5)
rowgap!(fig.layout, 5)
fig
save("./slides/imgs/part1_layout.png", fig)

#=
# saving at each step
GLMakie.activate!()
GLMakie.set_window_config!(float=true)
#GLMakie.set_window_config!(float=true, framerate=60)
#set_theme!(resolution=(600, 400))
Random.seed!(435)
fig = Figure(backgroundcolor = :ivory) # named colors
save("./slides/imgs/layout_1.png", fig)
Box(fig[1, 1:3]; color=rand(RGBAf), strokecolor=rand(RGBf))
save("./slides/imgs/layout_2.png", fig)
Box(fig[2, 1:3]; color=rand(RGBAf), strokecolor=rand(RGBf))
save("./slides/imgs/layout_3.png", fig)
Box(fig[3, 1:3]; color=rand(RGBAf), strokecolor=rand(RGBf))
save("./slides/imgs/layout_4.png", fig)
Box(fig[1:3, 1]; color=:transparent, strokecolor=:black, strokewidth = 2)
save("./slides/imgs/layout_5.png", fig)
Box(fig[1:3, 2]; color=:transparent, strokecolor=rand(RGBf))
save("./slides/imgs/layout_6.png", fig)
Box(fig[1:3, 3]; color=:transparent, strokecolor=rand(RGBf))
save("./slides/imgs/layout_7.png", fig)
Box(fig[:, 3, Right()]; color=(:orangered, 0.15))
save("./slides/imgs/layout_8.png", fig)
Label(fig[:, 3, Right()], "protrusion", textsize=18,
        rotation = π/ 2, padding=(3, 3, 3, 3))
save("./slides/imgs/layout_9.png", fig)
Box(fig[1, 1:3, Bottom()]; color=rand(RGBAf))
save("./slides/imgs/layout_10.png", fig)
Label(fig[1, 2, Bottom()], "protrusion")
save("./slides/imgs/layout_11.png", fig)
Box(fig[1:3, 1, TopLeft()]; color = (:white, 0.95))
save("./slides/imgs/layout_12.png", fig)
Label(fig[1:3, 1, TopLeft()], "(a)"; textsize=18, padding=(2, 2, 2, 2))
save("./slides/imgs/layout_13.png", fig)
Colorbar(fig[:,end+1])
save("./slides/imgs/layout_14.png", fig)
Label(fig[4,:], "My set of boxes")
save("./slides/imgs/layout_15.png", fig)
Label(fig[0,:], "Basic Layout", textsize = 24,
    color = :steelblue4, font = "TeX Gyre Heros Bold")
save("./slides/imgs/layout_16.png", fig)
colgap!(fig.layout, 5)
save("./slides/imgs/layout_17.png", fig)
rowgap!(fig.layout, 5)
save("./slides/imgs/layout_18.png", fig)
fig
=#